# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SofibMobile' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for Sofib
pod 'Alamofire', '~> 4.0'

target 'SofibMobileTests' do
inherit! :search_paths
# Pods for testing
end

target 'SofibMobileUITests' do
inherit! :search_paths
# Pods for testing
end

end